import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {count,deltaValue,day,reviewState,installFor} from './lib/security.mjs';
import {check,reviewEntries,FetchFailure,fetchSkill,sourceUrl} from './review.mjs';
import {dirRow,reviewedBadge} from './lib/parts.mjs';
import {loadContent} from './lib/data.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
let assertions=0;
const ok=(value,message)=>{assert.ok(value,message);assertions++;};
const equal=(actual,expected,message)=>{assert.deepEqual(actual,expected,message);assertions++;};
for(const bad of ['"><b data-fieldbook-probe="1">','2',{},-1,Infinity,NaN,Number.MAX_SAFE_INTEGER+1]) equal(count(bad),null,'Invalid counts remain unknown');
equal(count(0),0);equal(count(123),123);equal(deltaValue(-3),-3);equal(day('2026-02-30'),null);equal(day('2026-09-27'),'2026-09-27');
const {entries}=await loadContent(root);
const synthetic={...entries[0],stats:{installs:'"><b data-fieldbook-probe="1">',today:{},week:null,stars:1}};
ok(!dirRow(synthetic,'synthetic',0).includes('<b data-fieldbook-probe="1">'),'Invalid upstream data cannot become markup');
const text='---\nname: sample\ndescription: A sufficiently detailed sample engineering skill used only in local tests.\n---\nRead local project documentation.\n';
const checkedAt='2026-09-27';
const sample={id:'owner/repo/sample',repo:'owner/repo',path:'skills/sample/SKILL.md',skill:'sample'};
const good={...check(text,'sample'),checkedAt,source:sourceUrl(sample),status:'current'};
equal(reviewState(null).paused,true);equal(reviewState({...good,problems:['invalid']}).paused,true);
const flagged={...good,findings:[{rule:'git-force',line:2}]};
equal(reviewState(flagged,{cleared:{'git-force':'A defensive mention'}}).paused,true,'Rule-only exception cannot clear a finding');
equal(reviewState(flagged,{cleared:{'git-force':'A defensive mention'},clearedSha256:good.sha256}).paused,false);
equal(reviewState({...flagged,sha256:'a'.repeat(64)},{cleared:{'git-force':'A defensive mention'},clearedSha256:good.sha256}).paused,true,'Changed content invalidates old exception');
const paused={...entries[0],...reviewState(null)};
equal(installFor(paused),null);ok(!dirRow(paused,'paused',0).includes('data-copy='),'Paused row has no install copy button');ok(reviewedBadge(paused).includes('Review paused'));
const batch=Array.from({length:10},(_,i)=>({...sample,id:`owner/repo/sample-${i}`}));
const previous=Object.fromEntries(batch.map(e=>[e.id,{...good}]));
let result=await reviewEntries(batch,previous,{checkedAt,fetchText:async e=>{if(e.id.endsWith('-0'))throw new FetchFailure('network',true);return text;}});
equal(result.failed,1);equal(result.retained,1);equal(result.reviews[batch[0].id].sha256,good.sha256);equal(result.reviews[batch[0].id].checkedAt,good.checkedAt);ok(result.reviews[batch[0].id].retained,'Exactly10% failures retain good cache');
const before=JSON.stringify(previous);
await assert.rejects(()=>reviewEntries(batch,previous,{fetchText:async e=>{if(/-[01]$/.test(e.id))throw new FetchFailure('http-503',true);return text;}}),/>10%/);assertions++;equal(JSON.stringify(previous),before,'Outage abort cannot mutate prior reviews');
for(const kind of ['http-404','http-429','response-too-large']){
 result=await reviewEntries(batch,previous,{fetchText:async e=>{if(e.id.endsWith('-0'))throw new FetchFailure(kind,false);return text;}});
 equal(result.retained,0);equal(result.reviews[batch[0].id].status,'unavailable');
}
const badPrior={...previous,[batch[0].id]:flagged};
result=await reviewEntries(batch,badPrior,{fetchText:async e=>{if(e.id.endsWith('-0'))throw new FetchFailure('network',true);return text;}});
equal(result.retained,0,'A known-bad latest result cannot fall back to an older good one');
const newText=text+'\ngit push --force\n';
result=await reviewEntries(batch,previous,{fetchText:async()=>newText});
equal(result.retained,0);ok(result.reviews[batch[0].id].sha256!==good.sha256);ok(reviewState(result.reviews[batch[0].id]).paused,'New findings replace the previous good result');
result=await reviewEntries(batch,previous,{fetchText:async()=>text+'\nA harmless new line.\n'});
ok(result.reviews[batch[0].id].sha256!==good.sha256);equal(result.retained,0,'Changed clean file uses a fresh result');
result=await reviewEntries(batch,previous,{fetchText:async()=> 'invalid frontmatter'});ok(reviewState(result.reviews[batch[0].id]).paused);
const newPath=batch.map((e,i)=>i===0?{...e,path:'different/SKILL.md'}:e);
result=await reviewEntries(newPath,previous,{fetchText:async e=>{if(e.path.startsWith('different'))throw new FetchFailure('network',true);return text;}});equal(result.retained,0,'Cannot reuse a result for another source path');
for(const status of [404,429,500,503]) await assert.rejects(()=>fetchSkill('owner/repo','SKILL.md',{fetchImpl:async()=>new Response('',{status})}),e=>e instanceof FetchFailure&&e.retryable===(status>=500));assertions+=4;
await assert.rejects(()=>fetchSkill('owner/repo','SKILL.md',{fetchImpl:async()=>{throw new TypeError('offline');}}),e=>e.retryable);assertions++;
const workflow=await readFile(new URL('../.github/workflows/daily.yml',import.meta.url),'utf8');
ok(workflow.includes("if: github.ref == 'refs/heads/main'"));ok(workflow.includes("SYNC_GAP_MS: '2100'"));ok(workflow.includes('git add content/stats content/review.json vercel.json'));ok(!workflow.includes('always()'),'A failed review cannot run the commit step');
console.log(`Passed ${assertions} focused security assertions (offline fixtures; no provider calls).`);
